import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Montserrat as montse } from "next/font/google"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-switch/provider"

const fontSans = montse({
  subsets: ["latin"],
  variable: "--font-montse",
})


// Dynamic metadata
export async function generateMetadata() {
  return {
    title: {
      default: "Cafetería desde que Dios amanece",
      template: "%s | Cafetería desde que Dios amanece",
    },
    description: "Generated by create next app",
    icons: {
      icon: [
        './favicon.ico?v=4',
      ],
      apple: [
        '/apple-touch-icon.png?v=4',
      ],
      shortcut: [
        '/apple-touch-icon.png',
      ],
    },
    manifest: '/site.webmanifest',
  }
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={cn(
          "min-h-screen bg-background font-montse antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
